export interface SiteSettings {
    id: string;
    siteName: string | null;
    tagline: string | null;
    description: string | null;
    logoUrl: string | null;
    activeTheme?: string | null;
    brandColor?: string | null;
    brandPrimaryColor?: string | null;
    brandSecondaryColor?: string | null;
    brandAccentColor?: string | null;
    brandBackgroundColor?: string | null;
    brandTextColor?: string | null;
    brandFontPrimary?: string | null;
    brandFontSecondary?: string | null;
    brandFooterText?: string | null;
    brandSupportEmail?: string | null;
    footerAddress: string | null;
    footerCopyright: string | null;
    footerAboutText: string | null;
    socialFacebook: string | null;
    socialTwitter: string | null;
    socialInstagram: string | null;
    socialLinkedin: string | null;
    socialWhatsapp: string | null;
    socialTelegram: string | null;
    socialTiktok: string | null;
    socialYoutube: string | null;
    socialEmail?: string | null; // contactEmail
    contactEmail: string | null;
    headerStyle: string | null;
    headerBackgroundColor: string | null;
    headerTextColor: string | null;
    headerMobileBackgroundColor: string | null;
    footerBackgroundColor: string | null;
    footerTextColor: string | null;
    footerAddressBackgroundColor?: string | null;
    footerAddressTextColor?: string | null;
    showCart: boolean | null;
    showFloatingChat: boolean | null;
    whatsappNumber: string | null;
    seoTitle: string | null;
    seoKeywords: string | null;
    seoImage: string | null;
    faviconUrl: string | null;
    googleSiteVerificationId: string | null;
    googleAnalyticsId: string | null;
    metaPixelId?: string | null;
    tiktokPixelId?: string | null;
    googleTagManagerId?: string | null;
    enabledPosts: boolean | null;
    enabledPortfolio: boolean | null;
    enabledTestimonials: boolean | null;
    enabledGallery: boolean | null;
    enabledProducts: boolean | null;
    enabledOrders: boolean | null;
    enabledWhatsappCheckout?: boolean | null;
    enabledTaxonomies?: boolean | null;
    enabledInbox?: boolean | null;
    enabledCustomers?: boolean | null;
    themeConfig?: any;
    currency?: string | null;
    logoDisplayMode?: string | null;
    updatedAt: Date;
}

export type SiteSettingsUpdate = Partial<Omit<SiteSettings, "id" | "updatedAt">>;
