import { 
    countPostsInternal, 
    countTestimonialsInternal, 
    getMediaSizeInternal,
    getPagesInternal,
    getPageDetailInternal,
    savePageInternal,
    deletePageInternal,
    getTermsInternal,
    createTermInternal,
    deleteTermInternal,
    updateTermInternal,
    getMediaListInternal,
    uploadMediaInternal,
    deleteMediaInternal,
    getMediaFoldersInternal,
    createMediaFolderInternal,
    deleteMediaFolderInternal,
    searchAllInternal,
    getCredBuildPageInternal,
    saveCredBuildPageInternal,
    getMenuInternal,
    updateMenuInternal
} from "./actions";

// Facade / Client kontrak publik
export const ContentClient = {
    countPosts: countPostsInternal,
    countTestimonials: countTestimonialsInternal,
    getMediaSize: getMediaSizeInternal,
    getPages: getPagesInternal,
    getPageDetail: getPageDetailInternal,
    savePage: savePageInternal,
    deletePage: deletePageInternal,
    getTerms: getTermsInternal,
    createTerm: createTermInternal,
    deleteTerm: deleteTermInternal,
    updateTerm: updateTermInternal,
    getMediaList: getMediaListInternal,
    uploadMedia: uploadMediaInternal,
    deleteMedia: deleteMediaInternal,
    getMediaFolders: getMediaFoldersInternal,
    createMediaFolder: createMediaFolderInternal,
    deleteMediaFolder: deleteMediaFolderInternal,
    searchAll: searchAllInternal,
    getCredBuildPage: getCredBuildPageInternal,
    saveCredBuildPage: saveCredBuildPageInternal,
    getMenu: getMenuInternal,
    updateMenu: updateMenuInternal
};
