import { 
    countPostsInternal, 
    countTestimonialsInternal, 
    getMediaSizeInternal,
    getPagesInternal,
    getPageDetailInternal,
    savePageInternal,
    deletePageInternal,
    getTermsInternal,
    createTermInternal,
    deleteTermInternal,
    updateTermInternal,
    getMediaListInternal,
    uploadMediaInternal,
    deleteMediaInternal,
    getMediaFoldersInternal,
    createMediaFolderInternal,
    deleteMediaFolderInternal,
    searchAllInternal,
    getCredBuildPageInternal,
    saveCredBuildPageInternal,
    countMediaItemsInternal,
    countGalleryItemsInternal,
    countPortfolioItemsInternal,
    getPostInternal,
    getPostsInternal,
    getPageInternal,
    getGalleryItemsInternal,
    getPortfoliosInternal,
    getTestimonialsInternal
} from "./controllers/content.controller";
import {
    getMenuInternal,
    updateMenuInternal
} from "./controllers/menu.controller";

// Facade / Client kontrak publik
export const ContentClient = {
    countPosts: countPostsInternal,
    countTestimonials: countTestimonialsInternal,
    getMediaSize: getMediaSizeInternal,
    getPages: getPagesInternal,
    getPageDetail: getPageDetailInternal,
    savePage: savePageInternal,
    deletePage: deletePageInternal,
    getTerms: getTermsInternal,
    createTerm: createTermInternal,
    deleteTerm: deleteTermInternal,
    updateTerm: updateTermInternal,
    getMediaList: getMediaListInternal,
    uploadMedia: uploadMediaInternal,
    deleteMedia: deleteMediaInternal,
    getMediaFolders: getMediaFoldersInternal,
    createMediaFolder: createMediaFolderInternal,
    deleteMediaFolder: deleteMediaFolderInternal,
    searchAll: searchAllInternal,
    getCredBuildPage: getCredBuildPageInternal,
    saveCredBuildPage: saveCredBuildPageInternal,
    countMediaItems: countMediaItemsInternal,
    countGalleryItems: countGalleryItemsInternal,
    countPortfolioItems: countPortfolioItemsInternal,
    getMenu: getMenuInternal,
    updateMenu: updateMenuInternal,
    getPost: getPostInternal,
    getPosts: getPostsInternal,
    getPage: getPageInternal,
    getGalleryItems: getGalleryItemsInternal,
    getPortfolios: getPortfoliosInternal,
    getTestimonials: getTestimonialsInternal
};
