/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by CredBuild. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a CredBuild page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/credbuild/route.ts
 */

import nextDynamic from "next/dynamic";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { getPage } from "@/modules/page/ui/content-display";
import { hooks } from "@/lib/core/hooks";
import GallerySection from "@/components/ui/GallerySection";
import Script from "next/script";
import { headers } from "next/headers";
import { getBaseUrl } from "@/lib/domains/utils";

const Client = nextDynamic(() => import("./client").then(m => m.Client), {
    ssr: true,
    loading: () => <div className="min-h-screen bg-background animate-pulse" />
});

import TiptapRenderer from "@/components/editor/TiptapRenderer";
import { generateAutoExcerpt } from "@/lib/editor/render";
// Metadata generation
export async function generateMetadata({
  params,
}: {
  params: Promise<{ credbuildPath: string[] }>;
}): Promise<Metadata> {
  const { credbuildPath = [] } = await params;
  const path = `/${credbuildPath.join("/")}`;
  const pageData = await getPage(path);

  const ogTitle = pageData?.title || (pageData?.data as any)?.root?.props?.title;
  const ogDescription = pageData?.description || (pageData?.body ? generateAutoExcerpt(pageData.body) : undefined);

  const keywordsMeta = (pageData as any)?.metaData?.find((m: any) => m.key === "keywords");
  const keywords = keywordsMeta?.value || undefined;

  const noIndexMeta = (pageData as any)?.metaData?.find((m: any) => m.key === "noindex");
  const robots = noIndexMeta?.value === "true" ? { index: false, follow: true } : undefined;

  return {
    title: ogTitle,
    description: ogDescription,
    keywords,
    robots,

    openGraph: {
      ...(ogTitle && { title: ogTitle }),
      ...(ogDescription && { description: ogDescription }),
      images: pageData?.imageUrl ? [{ url: pageData.imageUrl }] : undefined,
    },
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ credbuildPath: string[] }>;
}) {
  const { credbuildPath = [] } = await params;
  const path = `/${credbuildPath.join("/")}`;
  let data = await getPage(path);

  // Apply filters to page data
  data = hooks.applyFilters("page_data", data, { path });

  if (!data) {
    return notFound();
  }

  const headersList = await headers();
  const host = headersList.get("host");
  const baseUrl = getBaseUrl(host);
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "headline": data.title || "Page",
    "description": data.description,
    "url": `${baseUrl}${path}`,
    "image": data.imageUrl ? [data.imageUrl] : undefined,
    "datePublished": data.createdAt,
    "dateModified": data.updatedAt,
  };

  // Render Visual Builder content if it exists and useBuilder is true
  if (data.useBuilder) {
    return (
      <>
        {jsonLd && (
          <Script
            id="ld-json-custom"
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
          />
        )}
        <Client data={data.data as any} />
      </>
    );
  }

  // If we have a standard body (Not using CredBuild), render it directly
  if (data.body && data.body !== "" && data.body !== "{}" && data.body !== '{"type":"doc","content":[]}') {
    return (
      <div className="min-h-screen bg-background text-foreground">
        <Script
          id="ld-json-body"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <div className="max-w-4xl mx-auto px-6 py-12 lg:px-8">
          <header className="mb-10 text-center">
            {data.title && <h1 className="text-4xl font-extrabold text-foreground sm:text-5xl tracking-tight">{data.title}</h1>}
          </header>
          <div className="prose dark:prose-invert max-w-none">
            <TiptapRenderer content={data.body} />
          </div>

          {/* Conditional Gallery Integration */}
          {Array.isArray((data as any).metaData) && 
           ((data as any).metaData as any[]).find((m: any) => m.key === 'show_gallery')?.value === 'true' && (
            <GallerySection />
          )}
        </div>
      </div>
    );
  }

  // Default fallback (empty builder canvas or not found)
  return (
    <>
      <Script
        id="ld-json-fallback"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Client data={data.data as any} />
    </>
  );
}

// Next.js will automatically detect dynamic rendering due to headers usage in the layout
// export const dynamic = "force-static";
